name: FinalTrial
version: '${project.version}'
main: es.outlook.adriansrj.finaltrial.FinalTrial
api-version: 1.17
authors: [ AdrianSR ]
depend: [Atlas]

commands:
  helloworld:
    description: Says hello world.
  menu:
    description: Opens the menu.
  hi:
    description: Hi people.
  item:
    description: NBT item.